openapi: 3.1.0
info:
  title: 'Ecommerce JaggerStore'
  version: '1.0.0'
  description: 'Documentacion para administrar los productos en API'
  contact:
    name: 'Nicolas Andreolli'
servers:
  - url: 'http://localhost:8080' 
paths:
  /carts:
    get:
      summary: Get all carts
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cart'
    post:
      summary: Create a new cart
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      producto:
                        type: string
                        format: ObjectId
                        description: ID of the product to add to the cart
                      cantidad:
                        type: number
                user:
                  type: object
                  properties:
                    email:
                      type: string
                purchase_datetime:
                  type: string
                  format: date-time
                code:
                  type: string
              required:
                - items
                - purchase_datetime
                - code
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'

  /carts/{cartId}:
    get:
      summary: Get a cart by ID
      parameters:
        - name: cartId
          in: path
          required: true
          description: ID of the cart
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
    put:
      summary: Update a cart by ID
      parameters:
        - name: cartId
          in: path
          required: true
          description: ID of the cart
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      producto:
                        type: string
                        format: ObjectId
                        description: ID of the product to add to the cart
                      cantidad:
                        type: number
                user:
                  type: object
                  properties:
                    email:
                      type: string
                purchase_datetime:
                  type: string
                  format: date-time
                code:
                  type: string
              required:
                - items
                - purchase_datetime
                - code
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
    delete:
      summary: Delete a cart by ID
      parameters:
        - name: cartId
          in: path
          required: true
          description: ID of the cart
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'

  /carts/{cartId}/items/{itemId}:
    delete:
      summary: Delete an item from the cart
      parameters:
        - name: cartId
          in: path
          required: true
          description: ID of the cart
          schema:
            type: string
        - name: itemId
          in: path
          required: true
          description: ID of the item to delete
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
components:
  schemas:
    Cart:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              producto:
                $ref: '#/components/schemas/Product'
              cantidad:
                type: number
        user:
          type: object
          properties:
            email:
              type: string
        purchase_datetime:
          type: string
          format: date-time
        code:
          type: string
      required:
        - items
        - purchase_datetime
        - code
